import 'controller/produk_three_controller.dart';import 'package:flutter/material.dart';import 'package:taternak13/core/app_export.dart';import 'package:taternak13/widgets/app_bar/appbar_leading_image.dart';import 'package:taternak13/widgets/app_bar/appbar_subtitle_two.dart';import 'package:taternak13/widgets/app_bar/custom_app_bar.dart';import 'package:taternak13/widgets/custom_outlined_button.dart';import 'package:taternak13/presentation/produk_two_dialog/produk_two_dialog.dart';import 'package:taternak13/presentation/produk_two_dialog/controller/produk_two_controller.dart';class ProdukThreeScreen extends GetWidget<ProdukThreeController> {const ProdukThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAtas(), SizedBox(height: 21.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle57, height: 225.v, width: 362.h, alignment: Alignment.center), SizedBox(height: 12.v), _buildSapiPotong(), SizedBox(height: 14.v), _buildFrame(), SizedBox(height: 14.v), Divider(color: appTheme.blueGray10002), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_jenis_pengiriman2".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 1.v), Container(width: 58.h, margin: EdgeInsets.only(left: 33.h), child: Text("msg_diantar_dijemput".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.justify, style: theme.textTheme.bodySmall!.copyWith(height: 1.69))), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_deskripsi_produk2".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 1.v), Align(alignment: Alignment.center, child: Container(width: 362.h, margin: EdgeInsets.only(left: 26.h, right: 25.h), child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.justify, style: CustomTextStyles.bodySmall_2.copyWith(height: 1.42)))), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_riwayat_penimbangan".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_senin_20_november".tr, style: CustomTextStyles.bodySmall_2)), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_senin_27_november".tr, style: CustomTextStyles.bodySmall_2)), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_senin_04_november".tr, style: CustomTextStyles.bodySmall_2)), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_senin_11_november".tr, style: CustomTextStyles.bodySmall_2))]))))])), bottomNavigationBar: _buildButton())); } 
/// Section Widget
Widget _buildAtas() { return Container(padding: EdgeInsets.symmetric(vertical: 12.v), decoration: AppDecoration.fillPrimary, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), CustomAppBar(leadingWidth: 49.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgRewindOnerrorcontainer, margin: EdgeInsets.only(left: 17.h, bottom: 1.v), onTap: () {onTapRewind();}), title: AppbarSubtitleTwo(text: "lbl_detail_produk".tr, margin: EdgeInsets.only(left: 11.h)))])); } 
/// Section Widget
Widget _buildSapiPotong() { return Container(width: double.maxFinite, padding: EdgeInsets.fromLTRB(26.h, 2.v, 26.h, 1.v), decoration: AppDecoration.outlineBlueGray, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_sapi_potong".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 5.v), Text("lbl_rp_18_000_000".tr, style: theme.textTheme.titleLarge)])), Padding(padding: EdgeInsets.only(bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(right: 18.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgMedicalHealth, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 2.v), child: Text("lbl_sehat".tr, style: CustomTextStyles.bodySmallGray500_1))])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Text("msg_jantan_siap_jual".tr, style: CustomTextStyles.bodySmall10)), SizedBox(height: 5.v), Text("lbl_400_700_kg".tr, style: theme.textTheme.bodyLarge)]))])); } 
/// Section Widget
Widget _buildFrame() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 23.h, right: 28.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage2025x25, height: 35.adaptSize, width: 35.adaptSize), Padding(padding: EdgeInsets.only(left: 14.h, top: 5.v, bottom: 5.v), child: Text("msg_peternak_sapi_kita".tr, style: theme.textTheme.bodyLarge)), Spacer(), CustomOutlinedButton(height: 26.v, width: 98.h, text: "lbl_kunjungi_profil".tr, margin: EdgeInsets.only(top: 3.v, bottom: 6.v), buttonStyle: CustomButtonStyles.outlineYellow, buttonTextStyle: theme.textTheme.bodySmall!, onPressed: () {onTapKunjungiProfil();})]))); } 
/// Section Widget
Widget _buildButton() { return Container(margin: EdgeInsets.only(left: 31.h, right: 39.h, bottom: 27.v), decoration: AppDecoration.fillOnErrorContainer, child: Container(decoration: AppDecoration.fillOnErrorContainer, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "lbl_keranjang2".tr, margin: EdgeInsets.only(right: 18.h), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.bodyMedium14_1, onPressed: () {onTapKeranjang();})), Expanded(child: CustomOutlinedButton(text: "lbl_beli_langsung".tr, margin: EdgeInsets.only(left: 18.h), onPressed: () {onTapBeliLangsung();}))]))); } 
/// Navigates to the profileScreen when the action is triggered.
onTapRewind() { Get.toNamed(AppRoutes.profileScreen, ); } 
/// Navigates to the profileTwoTabContainerScreen when the action is triggered.
onTapKunjungiProfil() { Get.toNamed(AppRoutes.profileTwoTabContainerScreen, ); } 

/// Displays a dialog with the [ProdukTwoDialog] content.
onTapKeranjang() { Get.dialog(AlertDialog(backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0), content:ProdukTwoDialog(Get.put(ProdukTwoController(),),),)); } 
/// Navigates to the checkoutScreen when the action is triggered.
onTapBeliLangsung() { Get.toNamed(AppRoutes.checkoutScreen, ); } 
 }
