import 'controller/keranjang_peternakan_controller.dart';import 'package:flutter/material.dart';import 'package:taternak13/core/app_export.dart';import 'package:taternak13/widgets/app_bar/appbar_leading_image.dart';import 'package:taternak13/widgets/app_bar/appbar_subtitle_two.dart';import 'package:taternak13/widgets/app_bar/custom_app_bar.dart';import 'package:taternak13/widgets/custom_outlined_button.dart';class KeranjangPeternakanScreen extends GetWidget<KeranjangPeternakanController> {const KeranjangPeternakanScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAtas(), SizedBox(height: 24.v), Expanded(child: SingleChildScrollView(child: _buildKeranjangPeternakan()))])), bottomNavigationBar: _buildButton())); } 
/// Section Widget
Widget _buildAtas() { return Container(decoration: AppDecoration.fillPrimary, child: Column(children: [SizedBox(height: 27.v), CustomAppBar(leadingWidth: 49.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgRewindOnerrorcontainer, margin: EdgeInsets.only(left: 17.h, bottom: 1.v)), title: AppbarSubtitleTwo(text: "lbl_pilih_ternak".tr, margin: EdgeInsets.only(left: 11.h)))])); } 
/// Section Widget
Widget _buildKeranjangPeternakan() { return Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 2.v), decoration: AppDecoration.outlineBlack9003, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 31.h, right: 34.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse252x52, height: 52.adaptSize, width: 52.adaptSize, radius: BorderRadius.circular(26.h)), Padding(padding: EdgeInsets.only(left: 21.h, top: 5.v, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ternak_segar".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 2.v), Text("msg_2_produk_dipilih".tr, style: CustomTextStyles.bodySmallGray700)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgCheckboxBlankCircleLine, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 16.v))])), SizedBox(height: 11.v), Divider(color: appTheme.gray40002)])), Container(padding: EdgeInsets.symmetric(vertical: 2.v), decoration: AppDecoration.outlineBlack9003, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 12.v), Padding(padding: EdgeInsets.symmetric(horizontal: 32.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage2025x25, height: 52.adaptSize, width: 52.adaptSize), Padding(padding: EdgeInsets.only(left: 21.h, top: 5.v, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_ternak_sapi_kita".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 2.v), Text("msg_1_produk_dipilih".tr, style: CustomTextStyles.bodySmallGray700)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgCheckboxblankcirclefill, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 16.v))])), SizedBox(height: 11.v), Divider(color: appTheme.gray40002)]))])); } 
/// Section Widget
Widget _buildButton() { return Container(margin: EdgeInsets.only(left: 31.h, right: 31.h, bottom: 22.v), decoration: AppDecoration.fillOnErrorContainer, child: CustomOutlinedButton(height: 42.v, text: "lbl_pilih".tr, buttonStyle: CustomButtonStyles.outlineOnErrorContainerTL201, buttonTextStyle: CustomTextStyles.bodyLargeOnErrorContainer, onPressed: () {onTapPilih();})); } 
/// Navigates to the keranjangProdukPeternakanScreen when the action is triggered.
onTapPilih() { Get.toNamed(AppRoutes.keranjangProdukPeternakanScreen, ); } 
 }
